/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application/Application.vue')['default']
    AppsIcon: typeof import('./src/components/Svg/AppsIcon.vue')['default']
    BreadItem: typeof import('./src/components/ProContainer/BreadItem.vue')['default']
    LeftOutlined: typeof import('./src/components/Svg/LeftOutlined.vue')['default']
    ProContainer: typeof import('./src/components/ProContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    VueP5Wrapper: typeof import('./src/components/VueP5Wrapper/index.vue')['default']
  }
}
