/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Application: typeof import('./../components/Application/Application.vue')['default']
    AppsIcon: typeof import('./../components/Svg/AppsIcon.vue')['default']
    BreadItem: typeof import('./../components/ProContainer/BreadItem.vue')['default']
    IconifyEpFold: typeof import('~icons/ep/fold')['default']
    'IconifyLogos:airbnb': typeof import('~icons/logos/airbnb')['default']
    LeftOutlined: typeof import('./../components/Svg/LeftOutlined.vue')['default']
    ProContainer: typeof import('./../components/ProContainer/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    VueP5Wrapper: typeof import('./../components/VueP5Wrapper/index.vue')['default']
  }
}
